const categories2 = {
  "Get to Know You": {
    "en": [
      "What's a fun fact most people don't know about you?",
      "What’s something you’re really passionate about?",
      "How do you usually spend your weekends?",
      "Do you prefer mornings or nights?",
      "What’s your go-to comfort food?",
      "What kind of music do you enjoy?",
      "What's a hobby you’ve always wanted to try?",
      "Do you consider yourself more introverted or extroverted?",
      "What’s a memory that always makes you smile?",
      "If you could instantly learn any skill, what would it be?",
      "Do you prefer beach holidays or city adventures?",
      "What's your favorite way to relax?",
      "Are you more of a planner or go-with-the-flow type?",
      "Do you believe in love at first sight?",
      "What’s a small thing that makes your day better?",
      "What’s your favorite season and why?",
      "What’s your favorite way to spend a day off?",
      "What’s a TV show or movie you can rewatch endlessly?",
      "What kind of pets do you like?",
      "What’s your idea of a perfect weekend?",
      "Do you enjoy trying new things or sticking to what you know?",
      "What’s a tradition you grew up with that you still love?",
      "What’s your favorite childhood memory?",
      "Are you more of a coffee or tea person?",
      "If you could live anywhere for a year, where would it be?",
      "What kind of people do you get along with best?",
      "Do you enjoy being in nature?",
      "What’s something you're currently learning or working on?",
      "If you had to describe yourself in three words, what would they be?",
      "What’s something people often get wrong about you?"
    ],
    "zh": [
      "说一个大多数人不知道的关于你的趣事？",
      "你最有热情的一件事是什么？",
      "你通常周末怎么过？",
      "你喜欢早上还是晚上？",
      "你最爱的安慰食物是什么？",
      "你喜欢什么类型的音乐？",
      "你一直想尝试的爱好是什么？",
      "你觉得自己是内向还是外向？",
      "哪段回忆总能让你微笑？",
      "如果你能立刻学会一项技能，那会是什么？",
      "你喜欢海边度假还是城市探险？",
      "你最喜欢的放松方式是什么？",
      "你是爱计划还是随性的人？",
      "你相信一见钟情吗？",
      "什么小事可以让你的一天更美好？",
      "你最喜欢哪个季节？为什么？",
      "你理想的一天假期是怎样的？",
      "哪部电影或剧你可以一遍遍看都不腻？",
      "你喜欢什么类型的宠物？",
      "你理想的周末是什么样的？",
      "你喜欢尝试新事物还是保持熟悉的方式？",
      "你小时候有什么传统现在还保留着？",
      "你最喜欢的童年记忆是什么？",
      "你更喜欢喝咖啡还是喝茶？",
      "如果能在任何地方住一年，你会选择哪里？",
      "你通常和哪种类型的人最合得来？",
      "你喜欢亲近大自然吗？",
      "你现在正在学或在做什么有趣的事？",
      "用三个词形容你自己？",
      "别人常常误解你的哪一点？"
    ],
    "zh_roman": [
      "Shuō yīgè dà duōshù rén bù zhīdào de guānyú nǐ de qùshì?",
      "Nǐ zuì yǒu rèqíng de yī jiàn shì shì shénme?",
      "Nǐ tōngcháng zhōumò zěnme guò?",
      "Nǐ xǐhuān zǎoshang háishì wǎnshàng?",
      "Nǐ zuì ài de ānwèi shíwù shì shénme?",
      "Nǐ xǐhuān shénme lèixíng de yīnyuè?",
      "Nǐ yīzhí xiǎng chángshì de àihào shì shénme?",
      "Nǐ juédé zìjǐ shì nèixiàng háishì wàixiàng?",
      "Nǎ duàn huíyì zǒng néng ràng nǐ wéixiào?",
      "Rúguǒ nǐ néng lìkè xuéhuì yī xiàng jìnéng, nà huì shì shénme?",
      "Nǐ xǐhuān hǎibiān dùjià háishì chéngshì tànxiǎn?",
      "Nǐ zuì xǐhuān de fàngsōng fāngshì shì shénme?",
      "Nǐ shì ài jìhuà háishì suíxìng de rén?",
      "Nǐ xiāngxìn yījiàn zhōngqíng ma?",
      "Shénme xiǎoshì kěyǐ ràng nǐ de yītiān gèng měihǎo?",
      "Nǐ zuì xǐhuān nǎge jìjié? Wèishéme?",
      "Nǐ lǐxiǎng de yītiān jiàqī shì zěnyàng de?",
      "Nǎ bù diànyǐng huò jù nǐ kěyǐ yī biàn biàn kàn dōu bù nì?",
      "Nǐ xǐhuān shénme lèixíng de chǒngwù?",
      "Nǐ lǐxiǎng de zhōumò shì shénme yàng de?",
      "Nǐ xǐhuān chángshì xīn shìwù háishì bǎochí shúxī de fāngshì?",
      "Nǐ xiǎoshíhòu yǒu shé me chuántǒng xiànzài hái bǎoliúzhe?",
      "Nǐ zuì xǐhuān de tóngnián jìyì shì shénme?",
      "Nǐ gèng xǐhuān hē kāfēi háishì hē chá?",
      "Rúguǒ néng zài rènhé dìfāng zhù yī nián, nǐ huì xuǎnzé nǎlǐ?",
      "Nǐ tōngcháng hé nǎ zhǒng lèixíng de rén zuì hé dé lái?",
      "Nǐ xǐhuān qīnjìn dà zìrán ma?",
      "Nǐ xiànzài zhèngzài xué huò zài zuò shénme yǒuqù de shì?",
      "Yòng sān gè cí xíngróng nǐ zìjǐ?",
      "Biérén chángcháng wùjiě nǐ de nǎ yī diǎn?"
    ]
  },
  "Hobbies": {
    en: [
      "What's a hobby you've always wanted to try?",
      "What's your weirdest hobby?",
      "How do you usually spend your weekends?",
      "Do you prefer creative or physical hobbies?",
      "What hobby makes you lose track of time?",
      "What's a hobby you picked up recently?",
      "If money and time weren’t a problem, what would you do for fun?",
      "Do you prefer indoor or outdoor hobbies?",
      "Is there a hobby you’d love to share with a partner?",
      "What’s something fun you used to do as a kid that you still enjoy?",
      "Have you ever taken a class just for fun?",
      "Do you collect anything?",
      "What hobby would surprise people about you?",
      "What hobby helps you relax the most?",
      "Do you enjoy making things with your hands?",
      "Have your hobbies changed over the years?",
      "What's something you'd love to get really good at?",
      "Do you enjoy learning hobbies together with someone else?",
      "What's a hobby you admire in others but don't do yourself?",
      "What hobby would be perfect for a weekend date?",
      "Do you like trying trending hobbies or stick to what you love?",
      "Have you ever turned a hobby into a side hustle?",
      "What's a hobby that brings you joy no matter what?",
      "What’s something your friends know you for?",
      "If you had a full day off, how would you spend it?"
    ],
    zh: [
      "你一直想尝试什么爱好？",
      "你最奇怪的爱好是什么？",
      "你周末通常怎么度过？",
      "你更喜欢创意类还是体力类爱好？",
      "什么爱好让你忘记时间？",
      "你最近开始了什么新爱好吗？",
      "如果时间和金钱不是问题，你最想玩什么？",
      "你喜欢室内还是户外的爱好？",
      "有没有一个爱好是你想和另一半一起做的？",
      "有没有小时候喜欢，现在还喜欢的活动？",
      "你有没有上过只是为了好玩儿的课？",
      "你有收集什么东西的习惯吗？",
      "有什么爱好是别人没想到你会有的？",
      "哪一个爱好最能让你放松？",
      "你喜欢自己动手做东西吗？",
      "你的爱好这些年来有没有改变？",
      "有什么事情是你特别想学会的？",
      "你喜欢和别人一起学新的兴趣吗？",
      "有没有一个你很欣赏但自己没尝试过的爱好？",
      "什么爱好最适合周末约会？",
      "你喜欢尝试流行的爱好吗，还是更喜欢自己熟悉的？",
      "你有没有把爱好变成副业？",
      "哪一个爱好无论何时都能带给你快乐？",
      "朋友们会因为哪个兴趣记住你？",
      "如果你有一天完全没事，你会怎么过？"
    ],
    zh_roman: [
      "Nǐ yīzhí xiǎng chángshì shénme àihào?",
      "Nǐ zuì qíguài de àihào shì shénme?",
      "Nǐ zhōumò tōngcháng zěnme dùguò?",
      "Nǐ gèng xǐhuān chuàngyì lèi háishì tǐlì lèi àihào?",
      "Shénme àihào ràng nǐ wàngjì shíjiān?",
      "Nǐ zuìjìn kāishǐle shénme xīn àihào ma?",
      "Rúguǒ shíjiān hé jīnqián bùshì wèntí, nǐ zuì xiǎng wán shénme?",
      "Nǐ xǐhuān shìnèi háishì hùwài de àihào?",
      "Yǒu méiyǒu yīgè àihào shì nǐ xiǎng hé lìng yībàn yīqǐ zuò de?",
      "Yǒu méiyǒu xiǎoshíhòu xǐhuān, xiànzài hái xǐhuān de huódòng?",
      "Nǐ yǒu méiyǒu shàngguò zhǐshì wèi le hǎowánr de kè?",
      "Nǐ yǒu shōují shénme dōngxī de xíguàn ma?",
      "Yǒu shénme àihào shì biérén méi xiǎngdào nǐ huì yǒu de?",
      "Nǎ yīgè àihào zuì néng ràng nǐ fàngsōng?",
      "Nǐ xǐhuān zìjǐ dòngshǒu zuò dōngxī ma?",
      "Nǐ de àihào zhèxiē nián lái yǒu méiyǒu gǎibiàn?",
      "Yǒu shénme shìqíng shì nǐ tèbié xiǎng xuéhuì de?",
      "Nǐ xǐhuān hé biérén yīqǐ xué xīn de xìngqù ma?",
      "Yǒu méiyǒu yīgè nǐ hěn xīnshǎng dàn zìjǐ méi chángshì guò de àihào?",
      "Shénme àihào zuì shìhé zhōumò yuēhuì?",
      "Nǐ xǐhuān chángshì liúxíng de àihào ma, háishì gèng xǐhuān zìjǐ shúxī de?",
      "Nǐ yǒu méiyǒu bǎ àihào biànchéng fùyè?",
      "Nǎ yīgè àihào wúlùn héshí dōu néng dài gěi nǐ kuàilè?",
      "Péngyǒu men huì yīnwèi nǎge xìngqù jìzhù nǐ?",
      "Rúguǒ nǐ yǒu yītiān wánquán méishì, nǐ huì zěnme guò?"
    ]
  }
};

const categories1 = {
  "Get to Know You": {
    "en": [
      "What's a fun fact most people don't know about you?",
      "What’s something you’re really passionate about?",
      "How do you usually spend your weekends?",
      "Do you prefer mornings or nights?",
      "What’s your go-to comfort food?",
      "What kind of music do you enjoy?",
      "What's a hobby you’ve always wanted to try?",
      "Do you consider yourself more introverted or extroverted?",
      "What’s a memory that always makes you smile?",
      "If you could instantly learn any skill, what would it be?",
      "Do you prefer beach holidays or city adventures?",
      "What's your favorite way to relax?",
      "Are you more of a planner or go-with-the-flow type?",
      "Do you believe in love at first sight?",
      "What’s a small thing that makes your day better?",
      "What’s your favorite season and why?",
      "What’s your favorite way to spend a day off?",
      "What’s a TV show or movie you can rewatch endlessly?",
      "What kind of pets do you like?",
      "What’s your idea of a perfect weekend?",
      "Do you enjoy trying new things or sticking to what you know?",
      "What’s a tradition you grew up with that you still love?",
      "What’s your favorite childhood memory?",
      "Are you more of a coffee or tea person?",
      "If you could live anywhere for a year, where would it be?",
      "What kind of people do you get along with best?",
      "Do you enjoy being in nature?",
      "What’s something you're currently learning or working on?",
      "If you had to describe yourself in three words, what would they be?",
      "What’s something people often get wrong about you?"
    ],
    "zh": [
      "说一个大多数人不知道的关于你的趣事？",
      "你最有热情的一件事是什么？",
      "你通常周末怎么过？",
      "你喜欢早上还是晚上？",
      "你最爱的安慰食物是什么？",
      "你喜欢什么类型的音乐？",
      "你一直想尝试的爱好是什么？",
      "你觉得自己是内向还是外向？",
      "哪段回忆总能让你微笑？",
      "如果你能立刻学会一项技能，那会是什么？",
      "你喜欢海边度假还是城市探险？",
      "你最喜欢的放松方式是什么？",
      "你是爱计划还是随性的人？",
      "你相信一见钟情吗？",
      "什么小事可以让你的一天更美好？",
      "你最喜欢哪个季节？为什么？",
      "你理想的一天假期是怎样的？",
      "哪部电影或剧你可以一遍遍看都不腻？",
      "你喜欢什么类型的宠物？",
      "你理想的周末是什么样的？",
      "你喜欢尝试新事物还是保持熟悉的方式？",
      "你小时候有什么传统现在还保留着？",
      "你最喜欢的童年记忆是什么？",
      "你更喜欢喝咖啡还是喝茶？",
      "如果能在任何地方住一年，你会选择哪里？",
      "你通常和哪种类型的人最合得来？",
      "你喜欢亲近大自然吗？",
      "你现在正在学或在做什么有趣的事？",
      "用三个词形容你自己？",
      "别人常常误解你的哪一点？"
    ],
    "zh_roman": [
      "Shuō yīgè dà duōshù rén bù zhīdào de guānyú nǐ de qùshì?",
      "Nǐ zuì yǒu rèqíng de yī jiàn shì shì shénme?",
      "Nǐ tōngcháng zhōumò zěnme guò?",
      "Nǐ xǐhuān zǎoshang háishì wǎnshàng?",
      "Nǐ zuì ài de ānwèi shíwù shì shénme?",
      "Nǐ xǐhuān shénme lèixíng de yīnyuè?",
      "Nǐ yīzhí xiǎng chángshì de àihào shì shénme?",
      "Nǐ juédé zìjǐ shì nèixiàng háishì wàixiàng?",
      "Nǎ duàn huíyì zǒng néng ràng nǐ wéixiào?",
      "Rúguǒ nǐ néng lìkè xuéhuì yī xiàng jìnéng, nà huì shì shénme?",
      "Nǐ xǐhuān hǎibiān dùjià háishì chéngshì tànxiǎn?",
      "Nǐ zuì xǐhuān de fàngsōng fāngshì shì shénme?",
      "Nǐ shì ài jìhuà háishì suíxìng de rén?",
      "Nǐ xiāngxìn yījiàn zhōngqíng ma?",
      "Shénme xiǎoshì kěyǐ ràng nǐ de yītiān gèng měihǎo?",
      "Nǐ zuì xǐhuān nǎge jìjié? Wèishéme?",
      "Nǐ lǐxiǎng de yītiān jiàqī shì zěnyàng de?",
      "Nǎ bù diànyǐng huò jù nǐ kěyǐ yī biàn biàn kàn dōu bù nì?",
      "Nǐ xǐhuān shénme lèixíng de chǒngwù?",
      "Nǐ lǐxiǎng de zhōumò shì shénme yàng de?",
      "Nǐ xǐhuān chángshì xīn shìwù háishì bǎochí shúxī de fāngshì?",
      "Nǐ xiǎoshíhòu yǒu shé me chuántǒng xiànzài hái bǎoliúzhe?",
      "Nǐ zuì xǐhuān de tóngnián jìyì shì shénme?",
      "Nǐ gèng xǐhuān hē kāfēi háishì hē chá?",
      "Rúguǒ néng zài rènhé dìfāng zhù yī nián, nǐ huì xuǎnzé nǎlǐ?",
      "Nǐ tōngcháng hé nǎ zhǒng lèixíng de rén zuì hé dé lái?",
      "Nǐ xǐhuān qīnjìn dà zìrán ma?",
      "Nǐ xiànzài zhèngzài xué huò zài zuò shénme yǒuqù de shì?",
      "Yòng sān gè cí xíngróng nǐ zìjǐ?",
      "Biérén chángcháng wùjiě nǐ de nǎ yī diǎn?"
    ]
  },
  "Hobbies": {
    en: [
      "What's a hobby you've always wanted to try?",
      "What's your weirdest hobby?",
      "How do you usually spend your weekends?",
      "Do you prefer creative or physical hobbies?",
      "What hobby makes you lose track of time?",
      "What's a hobby you picked up recently?",
      "If money and time weren’t a problem, what would you do for fun?",
      "Do you prefer indoor or outdoor hobbies?",
      "Is there a hobby you’d love to share with a partner?",
      "What’s something fun you used to do as a kid that you still enjoy?",
      "Have you ever taken a class just for fun?",
      "Do you collect anything?",
      "What hobby would surprise people about you?",
      "What hobby helps you relax the most?",
      "Do you enjoy making things with your hands?",
      "Have your hobbies changed over the years?",
      "What's something you'd love to get really good at?",
      "Do you enjoy learning hobbies together with someone else?",
      "What's a hobby you admire in others but don't do yourself?",
      "What hobby would be perfect for a weekend date?",
      "Do you like trying trending hobbies or stick to what you love?",
      "Have you ever turned a hobby into a side hustle?",
      "What's a hobby that brings you joy no matter what?",
      "What’s something your friends know you for?",
      "If you had a full day off, how would you spend it?"
    ],
    zh: [
      "你一直想尝试什么爱好？",
      "你最奇怪的爱好是什么？",
      "你周末通常怎么度过？",
      "你更喜欢创意类还是体力类爱好？",
      "什么爱好让你忘记时间？",
      "你最近开始了什么新爱好吗？",
      "如果时间和金钱不是问题，你最想玩什么？",
      "你喜欢室内还是户外的爱好？",
      "有没有一个爱好是你想和另一半一起做的？",
      "有没有小时候喜欢，现在还喜欢的活动？",
      "你有没有上过只是为了好玩儿的课？",
      "你有收集什么东西的习惯吗？",
      "有什么爱好是别人没想到你会有的？",
      "哪一个爱好最能让你放松？",
      "你喜欢自己动手做东西吗？",
      "你的爱好这些年来有没有改变？",
      "有什么事情是你特别想学会的？",
      "你喜欢和别人一起学新的兴趣吗？",
      "有没有一个你很欣赏但自己没尝试过的爱好？",
      "什么爱好最适合周末约会？",
      "你喜欢尝试流行的爱好吗，还是更喜欢自己熟悉的？",
      "你有没有把爱好变成副业？",
      "哪一个爱好无论何时都能带给你快乐？",
      "朋友们会因为哪个兴趣记住你？",
      "如果你有一天完全没事，你会怎么过？"
    ],
    zh_roman: [
      "Nǐ yīzhí xiǎng chángshì shénme àihào?",
      "Nǐ zuì qíguài de àihào shì shénme?",
      "Nǐ zhōumò tōngcháng zěnme dùguò?",
      "Nǐ gèng xǐhuān chuàngyì lèi háishì tǐlì lèi àihào?",
      "Shénme àihào ràng nǐ wàngjì shíjiān?",
      "Nǐ zuìjìn kāishǐle shénme xīn àihào ma?",
      "Rúguǒ shíjiān hé jīnqián bùshì wèntí, nǐ zuì xiǎng wán shénme?",
      "Nǐ xǐhuān shìnèi háishì hùwài de àihào?",
      "Yǒu méiyǒu yīgè àihào shì nǐ xiǎng hé lìng yībàn yīqǐ zuò de?",
      "Yǒu méiyǒu xiǎoshíhòu xǐhuān, xiànzài hái xǐhuān de huódòng?",
      "Nǐ yǒu méiyǒu shàngguò zhǐshì wèi le hǎowánr de kè?",
      "Nǐ yǒu shōují shénme dōngxī de xíguàn ma?",
      "Yǒu shénme àihào shì biérén méi xiǎngdào nǐ huì yǒu de?",
      "Nǎ yīgè àihào zuì néng ràng nǐ fàngsōng?",
      "Nǐ xǐhuān zìjǐ dòngshǒu zuò dōngxī ma?",
      "Nǐ de àihào zhèxiē nián lái yǒu méiyǒu gǎibiàn?",
      "Yǒu shénme shìqíng shì nǐ tèbié xiǎng xuéhuì de?",
      "Nǐ xǐhuān hé biérén yīqǐ xué xīn de xìngqù ma?",
      "Yǒu méiyǒu yīgè nǐ hěn xīnshǎng dàn zìjǐ méi chángshì guò de àihào?",
      "Shénme àihào zuì shìhé zhōumò yuēhuì?",
      "Nǐ xǐhuān chángshì liúxíng de àihào ma, háishì gèng xǐhuān zìjǐ shúxī de?",
      "Nǐ yǒu méiyǒu bǎ àihào biànchéng fùyè?",
      "Nǎ yīgè àihào wúlùn héshí dōu néng dài gěi nǐ kuàilè?",
      "Péngyǒu men huì yīnwèi nǎge xìngqù jìzhù nǐ?",
      "Rúguǒ nǐ yǒu yītiān wánquán méishì, nǐ huì zěnme guò?"
    ]
  },
  "Fun Facts": {
    en: [
      "What's a fun fact most people don't know about you?",
      "What's the weirdest thing you’ve ever eaten?",
      "Can you do any impressions or party tricks?",
      "What’s a random talent you have?",
      "What’s the most unusual job you’ve ever had?",
      "What’s your most useless hidden talent?",
      "Have you ever won a random competition or contest?",
      "What’s the most spontaneous thing you've ever done?",
      "What’s the strangest coincidence you've experienced?",
      "Have you ever met a celebrity? Who?",
      "Do you have a strange phobia?",
      "What’s your most unique nickname?",
      "Have you ever had a funny wardrobe malfunction?",
      "What’s the weirdest compliment you’ve ever received?",
      "Can you speak in any accents?",
      "What’s your go-to karaoke song?",
      "Have you ever been on TV or in a newspaper?",
      "Do you believe in any superstitions?",
      "What’s the quirkiest thing you own?",
      "Have you ever had a really funny dream?",
      "Do you have any weird habits or rituals?",
      "What’s a childhood belief you had that turned out to be wrong?",
      "Have you ever done something really embarrassing in public?",
      "Do you have any unusual collections?",
      "What’s the most random thing on your bucket list?"
    ],
    zh: [
      "别人不知道你的有趣事实是什么？",
      "你吃过最奇怪的食物是什么？",
      "你会表演模仿或派对技巧吗？",
      "你有什么冷门技能？",
      "你做过最不寻常的工作是什么？",
      "你最没用但隐藏的技能是什么？",
      "你有没有赢过什么随机比赛或抽奖？",
      "你做过最即兴的事情是什么？",
      "你经历过最奇妙的巧合是什么？",
      "你遇到过名人吗？是谁？",
      "你有奇怪的恐惧症吗？",
      "你最特别的外号是什么？",
      "你有没有穿衣出糗过？",
      "你收到过最奇怪的称赞是什么？",
      "你会用不同口音说话吗？",
      "你最常唱的卡拉OK歌曲是什么？",
      "你上过电视或上过报纸吗？",
      "你相信任何迷信吗？",
      "你拥有的最古怪的东西是什么？",
      "你做过最搞笑的梦是什么？",
      "你有奇怪的习惯或小仪式吗？",
      "你小时候相信却后来发现是错的事情是什么？",
      "你有没有在公众场合做过超尴尬的事？",
      "你有收集什么特别的东西吗？",
      "你愿望清单里最奇怪的一项是什么？"
    ],
    zh_roman: [
      "Biérén bù zhīdào nǐ de yǒuqù shìshí shì shénme?",
      "Nǐ chīguò zuì qíguài de shíwù shì shénme?",
      "Nǐ huì biǎoyǎn mófǎng huò pàiduì jìqiǎo ma?",
      "Nǐ yǒu shénme lěngmén jìnéng?",
      "Nǐ zuòguò zuì bù xúnyáng de gōngzuò shì shénme?",
      "Nǐ zuì méiyòng dàn cángzhe de jìnéng shì shénme?",
      "Nǐ yǒu méiyǒu yíngguò shénme suíjī bǐsài huò chōujiǎng?",
      "Nǐ zuòguò zuì jíxìng de shìqíng shì shénme?",
      "Nǐ jīnglì guò zuì qímiào de qiǎohé shì shénme?",
      "Nǐ yùdào guò míngrén ma? Shì shéi?",
      "Nǐ yǒu qíguài de kǒngjù zhèng ma?",
      "Nǐ zuì tèbié de wàihào shì shénme?",
      "Nǐ yǒu méiyǒu chuānyī chūqiǔ guò?",
      "Nǐ shōudào guò zuì qíguài de chēngzàn shì shénme?",
      "Nǐ huì yòng bùtóng kǒuyīn shuōhuà ma?",
      "Nǐ zuì cháng chàng de Kǎlā OK gēqǔ shì shénme?",
      "Nǐ shàngguò diànshì huò shàngguò bàozhǐ ma?",
      "Nǐ xiāngxìn rènhé míxìn ma?",
      "Nǐ yǒngyǒu de zuì gǔguài de dōngxī shì shénme?",
      "Nǐ zuì gǎoxiào de mèng shì shénme?",
      "Nǐ yǒu qíguài de xíguàn huò xiǎo yíshì ma?",
      "Nǐ xiǎoshíhòu xiāngxìn què hòulái fāxiàn shì cuò de shìqíng shì shénme?",
      "Nǐ yǒu méiyǒu zài gōngzhòng chǎnghé zuòguò chāo gāngà de shì?",
      "Nǐ yǒu shōují shénme tèbié de dōngxī ma?",
      "Nǐ yuànwàng qīngdān lǐ zuì qíguài de yī xiàng shì shénme?"
    ]
  },
  "Career": {
    en: [
      "What job would you choose if money weren't a factor?",
      "What's your biggest career goal right now?",
      "What's a skill you wish you had for your job?",
      "Have you ever completely switched careers?",
      "What's your dream company to work for?",
      "What do you do for work, and do you enjoy it?",
      "Did you always want to do what you're doing now?",
      "What’s something about your job that makes you feel proud?",
      "Do you see yourself doing the same job in 5 years?",
      "What’s a career dream you haven’t given up on?",
      "Would you prefer a high-paying job or a meaningful one?",
      "How important is work-life balance to you?",
      "What kind of work would you do if you didn’t have to worry about money?",
      "Have your career goals changed over the years?",
      "How does your job reflect your personality?",
      "What’s something your job has taught you about people?",
      "Do you like talking about work when you're off the clock?",
      "If your partner had to move for work, would you consider relocating?",
      "How do you usually handle work stress?",
      "Do you like routine or variety in your job?",
      "What’s something funny or strange that’s happened at your job?",
      "If you could shadow someone for a day, who would it be?",
      "Would you ever consider working together with your partner?",
      "Do you value ambition in a partner?",
      "What’s your ideal work schedule?",
      "How do you unwind after a long day at work?",
      "What’s one thing you'd love your future partner to understand about your job?",
      "Have you ever had a work crush?",
      "How do you balance career goals and relationship goals?",
      "If you could switch jobs with someone for a day, who would it be?"
    ],
    zh: [
      "如果不用担心钱，你想做什么工作？",
      "你目前最大的职业目标是什么？",
      "你希望拥有哪项职业技能？",
      "你是否曾经完全换过职业？",
      "你梦想为哪家公司工作？",
      "你现在做什么工作？你喜欢这份工作吗？",
      "你一直都想做现在这份工作吗？",
      "你工作中最让你感到骄傲的是什么？",
      "你觉得五年后你还会做现在这份工作吗？",
      "你有没有一个还没放弃的职业梦想？",
      "你更想要高薪的工作还是有意义的工作？",
      "你觉得工作与生活的平衡重要吗？",
      "如果不用担心钱，你想做什么工作？",
      "你的职业目标有随着时间改变吗？",
      "你的工作是否体现了你的性格？",
      "你的工作教会你关于人的什么？",
      "下班后你还喜欢聊工作吗？",
      "如果你的另一半因为工作要搬家，你会考虑跟着搬吗？",
      "你通常怎么应对工作的压力？",
      "你喜欢有规律还是多变化的工作？",
      "工作中有没有发生过什么好笑或奇怪的事？",
      "如果你可以跟任何人共事一天，你会选谁？",
      "你会考虑和伴侣一起工作吗？",
      "你在伴侣身上重视“上进心”吗？",
      "你理想的工作时间安排是怎样的？",
      "你下班后通常怎么放松？",
      "你希望未来的另一半了解你工作的哪一方面？",
      "你有没有过“职场暗恋”？",
      "你怎么在职业目标和感情目标中取得平衡？",
      "如果你能和任何人换工作一天，你会选谁？"
    ],
    zh_roman: [
      "Rúguǒ bùyòng dānxīn qián, nǐ xiǎng zuò shénme gōngzuò?",
      "Nǐ mùqián zuìdà de zhíyè mùbiāo shì shénme?",
      "Nǐ xīwàng yǒngyǒu nǎ xiàng zhíyè jìnéng?",
      "Nǐ shìfǒu céngjīng wánquán huànguò zhíyè?",
      "Nǐ mèngxiǎng wèi nǎ jiā gōngsī gōngzuò?",
      "Nǐ xiànzài zuò shénme gōngzuò? Nǐ xǐhuān zhè fèn gōngzuò ma?",
      "Nǐ yīzhí dōu xiǎng zuò xiànzài zhè fèn gōngzuò ma?",
      "Nǐ gōngzuò zhōng zuì ràng nǐ gǎndào jiāo'ào de shì shénme?",
      "Nǐ juéde wǔ nián hòu hái huì zuò xiànzài zhè fèn gōngzuò ma?",
      "Nǐ yǒu méiyǒu yīgè hái méi fàngqì de zhíyè mèngxiǎng?",
      "Nǐ gèng xiǎng yào gāoxīn de gōngzuò háishì yǒu yìyì de gōngzuò?",
      "Nǐ juéde gōngzuò yǔ shēnghuó de pínghéng zhòngyào ma?",
      "Rúguǒ bùyòng dānxīn qián, nǐ xiǎng zuò shénme gōngzuò?",
      "Nǐ de zhíyè mùbiāo yǒu suízhe shíjiān gǎibiàn ma?",
      "Nǐ de gōngzuò shìfǒu tǐxiànle nǐ de xìnggé?",
      "Nǐ de gōngzuò jiàohuì nǐ guānyú rén de shénme?",
      "Xiàbān hòu nǐ hái xǐhuān liáo gōngzuò ma?",
      "Rúguǒ nǐ de lìng yī bàn yīnwèi gōngzuò yào bānjiā, nǐ huì kǎolǜ gēnzhe bān ma?",
      "Nǐ tōngcháng zěnme yìngduì gōngzuò de yālì?",
      "Nǐ xǐhuān yǒu guīlǜ háishì duō biànhuà de gōngzuò?",
      "Gōngzuò zhōng yǒu méiyǒu fāshēng guò shénme hǎoxiào huò qíguài de shì?",
      "Rúguǒ nǐ kěyǐ gēn rènhé rén gòngshì yītiān, nǐ huì xuǎn shuí?",
      "Nǐ huì kǎolǜ hé bànlǚ yīqǐ gōngzuò ma?",
      "Nǐ zài bànlǚ shēnshang zhòngshì 'shàngjìnxīn' ma?",
      "Nǐ lǐxiǎng de gōngzuò shíjiān ānpái shì zěnyàng de?",
      "Nǐ xiàbān hòu tōngcháng zěnme fàngsōng?",
      "Nǐ xīwàng wèilái de lìng yī bàn liǎojiě nǐ gōngzuò de nǎ yī fāngmiàn?",
      "Nǐ yǒu méiyǒu guò 'zhíchǎng ànliàn'?",
      "Nǐ zěnme zài zhíyè mùbiāo hé gǎnqíng mùbiāo zhōng qǔdé pínghéng?",
      "Rúguǒ nǐ néng hé rènhé rén huàn gōngzuò yītiān, nǐ huì xuǎn shuí?"
    ]
  },
  "Travel": {
    en: [
      "What's your top travel destination?",
      "Do you prefer mountains or beaches?",
      "What's a city you could visit over and over?",
      "Have you ever traveled solo?",
      "What's your funniest travel story?",
      "What's your dream travel destination as a couple?",
      "Do you like spontaneous trips or well-planned ones?",
      "What's one place you'd love to go with your future partner?",
      "City escape or nature retreat — which one excites you more?",
      "Do you prefer traveling with a group or just one person?",
      "What’s the most romantic place you've been to?",
      "If we could go anywhere this weekend, where would you suggest?",
      "Do you like trying local street food when traveling?",
      "What’s one travel memory that still makes you smile?",
      "What's the most adventurous thing you've done while traveling?",
      "Are you more of a suitcase or backpack kind of traveler?",
      "Would you enjoy a road trip with your partner?",
      "What's your travel personality: chill, explorer, or planner?",
      "Do you collect anything when you travel?",
      "Have you ever had a travel experience that changed you?",
      "What’s your go-to travel snack or comfort food?",
      "Is there a country you’ve visited that felt like home?",
      "How do you handle travel mishaps or delays?",
      "Would you try a couple’s trip early in a relationship?",
      "What’s your idea of a perfect holiday?",
      "Do you prefer luxury resorts or budget stays with local vibes?",
      "What destination is top of your bucket list right now?",
      "Have you ever fallen in love with a place — or a person — while traveling?",
      "Would you rather travel every month or live in one dream city forever?",
      "What does your dream honeymoon look like?"
    ],
    zh: [
      "你最想去哪个旅行目的地？",
      "你喜欢山还是海？",
      "哪个城市你想一去再去？",
      "你有没有一个人旅行过？",
      "你最搞笑的旅行经历是什么？",
      "你梦想和另一半一起去哪里旅行？",
      "你喜欢说走就走的旅行，还是计划好的？",
      "有没有一个地方你很想和未来的伴侣一起去？",
      "城市度假还是大自然冒险，你更喜欢哪一个？",
      "你喜欢和一群人旅行，还是和一个人？",
      "你去过最浪漫的地方是哪里？",
      "如果这个周末可以去任何地方，你会建议去哪？",
      "你旅行时喜欢尝试当地小吃吗？",
      "有没有一个旅行回忆让你现在想起来还会笑？",
      "旅行中你做过最冒险的事情是什么？",
      "你是行李箱派还是背包派？",
      "你会喜欢和伴侣一起公路旅行吗？",
      "你的旅行风格是轻松、探险还是计划型？",
      "你旅行时会收集什么纪念品吗？",
      "有没有一次旅行经历让你有所改变？",
      "你旅行时最喜欢带什么零食或安慰食物？",
      "你有没有去过一个国家，感觉像“家”？",
      "如果遇到旅行延误或意外，你通常怎么应对？",
      "你会在感情初期就去情侣旅行吗？",
      "你理想的假期是什么样的？",
      "你更喜欢豪华度假村，还是有当地氛围的平价住宿？",
      "你现在最想打卡的旅行地是哪里？",
      "你有没有在旅行中爱上一个地方，或者一个人？",
      "你想每个月都旅行一次，还是一直住在一个梦想城市？",
      "你梦想中的蜜月旅行是怎样的？"
    ],
    zh_roman: [
      "Nǐ zuì xiǎng qù nǎge lǚxíng mùdìdì?",
      "Nǐ xǐhuān shān háishì hǎi?",
      "Nǎge chéngshì nǐ xiǎng yī qù zài qù?",
      "Nǐ yǒu méiyǒu yīgè rén lǚxíng guò?",
      "Nǐ zuì gǎoxiào de lǚxíng jīnglì shì shénme?",
      "Nǐ mèngxiǎng hé lìng yī bàn yīqǐ qù nǎlǐ lǚxíng?",
      "Nǐ xǐhuān shuō zǒu jiù zǒu de lǚxíng, háishì jìhuà hǎo de?",
      "Yǒu méiyǒu yīgè dìfāng nǐ hěn xiǎng hé wèilái de bànlǚ yīqǐ qù?",
      "Chéngshì dùjià háishì dà zìrán màoxiǎn, nǐ gèng xǐhuān nǎ yī gè?",
      "Nǐ xǐhuān hé yīqún rén lǚxíng, háishì hé yīgè rén?",
      "Nǐ qùguò zuì làngmàn de dìfāng shì nǎlǐ?",
      "Rúguǒ zhè gè zhōumò kěyǐ qù rènhé dìfāng, nǐ huì jiànyì qù nǎlǐ?",
      "Nǐ lǚxíng shí xǐhuān chángshì dāngdì xiǎochī ma?",
      "Yǒu méiyǒu yīgè lǚxíng huíyì ràng nǐ xiànzài xiǎng qǐlái hái huì xiào?",
      "Lǚxíng zhōng nǐ zuòguò zuì màoxiǎn de shìqíng shì shénme?",
      "Nǐ shì xínglǐxiāng pài háishì bèibāo pài?",
      "Nǐ huì xǐhuān hé bànlǚ yīqǐ gōnglù lǚxíng ma?",
      "Nǐ de lǚxíng fēnggé shì qīngsōng, tànxiǎn háishì jìhuà xíng?",
      "Nǐ lǚxíng shí huì shōují shénme jìniànpǐn ma?",
      "Yǒu méiyǒu yī cì lǚxíng jīnglì ràng nǐ yǒu suǒ gǎibiàn?",
      "Nǐ lǚxíng shí zuì xǐhuān dài shénme língshí huò ānwèi shíwù?",
      "Nǐ yǒu méiyǒu qùguò yīgè guójiā, gǎnjué xiàng 'jiā'?",
      "Rúguǒ yùdào lǚxíng yánwù huò yìwài, nǐ tōngcháng zěnme yìngduì?",
      "Nǐ huì zài gǎnqíng chūqī jiù qù qínglǚ lǚxíng ma?",
      "Nǐ lǐxiǎng de jiàqī shì shénme yàng de?",
      "Nǐ gèng xǐhuān háohuá dùjiàcūn, háishì yǒu dāngdì fēnwéi de píngjià zhùsù?",
      "Nǐ xiànzài zuì xiǎng dǎkǎ de lǚxíng dì shì nǎlǐ?",
      "Nǐ yǒu méiyǒu zài lǚxíng zhōng ài shàng yīgè dìfāng, huòzhě yīgè rén?",
      "Nǐ xiǎng měi gè yuè dōu lǚxíng yīcì, háishì yīzhí zhù zài yīgè mèngxiǎng chéngshì?",
      "Nǐ mèngxiǎng zhōng de mìyuè lǚxíng shì zěnyàng de?"
    ]
  },
  "Reflection": {
    "en": [
      "What is one belief you’ve changed your mind about?",
      "Do you think people are inherently good or bad?",
      "What’s something you used to value but no longer do?",
      "If you could ask the universe one question, what would it be?",
      "What does 'success' mean to you?",
      "Is happiness a choice or a result?",
      "Do we have free will, or is everything predetermined?",
      "Would you want to know the exact day you’ll die?",
      "If you could relive one moment in your life, which would it be?",
      "What scares you the most about getting older?",
      "Are people defined more by their actions or their intentions?",
      "Can money really buy happiness?",
      "What do you think is humanity’s greatest strength?",
      "If you had unlimited time but no money, what would you do?",
      "What’s something most people take for granted?",
      "Do you believe everything happens for a reason?",
      "What’s a truth you find hard to accept?",
      "What does 'home' mean to you?",
      "Do you think suffering is necessary for growth?",
      "How do you define a meaningful life?",
      "What’s more important: truth or kindness?",
      "Is love more of a feeling or a choice?",
      "Can you truly know yourself without others?",
      "If you had to live the same day forever, what would that day look like?",
      "What would you do if you knew you couldn’t fail?",
      "What’s one thing you hope to be remembered for?",
      "Would you rather be respected or liked?",
      "If you had to start your life over, what would you do differently?",
      "What’s something you’ll never understand?",
      "If you could fix one problem in the world, what would it be?",
      "What role does pain play in your life?",
      "Do you think people can really change?",
      "What does it mean to be wise?",
      "What’s the biggest illusion people live under?",
      "What’s more valuable: time or money?",
      "What is one thing you'd tell your younger self?",
      "Do you think we live in a simulation?",
      "Is it more important to be right or to understand?",
      "What’s something you believe that most people don’t?",
      "If today was your last day, what would you do?"
    ],
    "zh": [
      "你曾经改变过的一个信念是什么？",
      "你认为人性本善还是本恶？",
      "有什么是你曾经很看重但现在不再重视的？",
      "如果你可以问宇宙一个问题，你会问什么？",
      "“成功”对你来说意味着什么？",
      "幸福是一种选择还是一种结果？",
      "你认为人有自由意志吗，还是一切早已注定？",
      "你想知道自己死亡的确切日期吗？",
      "如果你可以重来一次人生中的某一刻，会是哪一刻？",
      "你最害怕变老的什么方面？",
      "一个人是由行为定义，还是由意图定义？",
      "金钱真的能买来幸福吗？",
      "你认为人类最大的优点是什么？",
      "如果你有无限的时间但没有钱，你会做什么？",
      "有什么是大多数人都理所当然的？",
      "你相信万事皆有因吗？",
      "有什么真相是你难以接受的？",
      "“家”对你来说意味着什么？",
      "你认为痛苦对成长有必要吗？",
      "你如何定义有意义的人生？",
      "哪一个更重要：真实还是善良？",
      "爱更像是一种感觉还是一种选择？",
      "没有他人，你能真正了解自己吗？",
      "如果你必须永远活在同一天，那会是哪一天？",
      "如果你知道自己不会失败，你会做什么？",
      "你希望人们记住你的一件事是什么？",
      "你更想被尊重还是被喜欢？",
      "如果你能重新开始人生，你会改变什么？",
      "有什么是你永远无法理解的？",
      "如果你可以解决世界上的一个问题，会是什么？",
      "痛苦在你的人生中扮演着怎样的角色？",
      "你觉得人真的可以改变吗？",
      "你认为智慧的定义是什么？",
      "人们生活中最大的错觉是什么？",
      "时间和金钱哪个更有价值？",
      "如果你能对小时候的自己说一句话，会说什么？",
      "你觉得我们生活在虚拟世界中吗？",
      "正确重要，还是理解重要？",
      "你相信但大多数人不相信的一件事是什么？",
      "如果今天是你生命中的最后一天，你会做什么？"
    ],
    "zh_roman": [
      "Nǐ céngjīng gǎibiàn guò de yī gè xìnniàn shì shénme?",
      "Nǐ rènwéi rénxìng běnshàn háishì běn'è?",
      "Yǒu shénme shì nǐ céngjīng hěn kànzhòng dàn xiànzài bú zài zhòngshì de?",
      "Rúguǒ nǐ kěyǐ wèn yǔzhòu yī gè wèntí, nǐ huì wèn shénme?",
      "“Chénggōng” duì nǐ lái shuō yìwèi zhe shénme?",
      "Xìngfú shì yì zhǒng xuǎnzé háishì yì zhǒng jiéguǒ?",
      "Nǐ rènwéi rén yǒu zìyóu yìzhì ma, háishì yīqiè zǎo yǐ zhùdìng?",
      "Nǐ xiǎng zhīdào zìjǐ sǐwáng de quèqiè rìqī ma?",
      "Rúguǒ nǐ kěyǐ chónglái yí cì rénshēng zhōng de mǒu yīkè, huì shì nǎ yīkè?",
      "Nǐ zuì hàipà biànlǎo de shénme fāngmiàn?",
      "Yí gè rén shì yóu xíngwéi dìngyì, háishì yóu yìtú dìngyì?",
      "Jīnqián zhēnde néng mǎi dào xìngfú ma?",
      "Nǐ rènwéi rénlèi zuìdà de yōudiǎn shì shénme?",
      "Rúguǒ nǐ yǒu wúxiàn de shíjiān dàn méiyǒu qián, nǐ huì zuò shénme?",
      "Yǒu shé me shì dàduōshù rén dōu lǐsuǒdāngrán de?",
      "Nǐ xiāngxìn wànshì jiē yǒu yīn ma?",
      "Yǒu shé me zhēnxiàng shì nǐ nányǐ jiēshòu de?",
      "“Jiā” duì nǐ lái shuō yìwèi zhe shénme?",
      "Nǐ rènwéi tòngkǔ duì chéngzhǎng yǒu bìyào ma?",
      "Nǐ rúhé dìngyì yǒuyìyì de rénshēng?",
      "Nǎ yīgè gèng zhòngyào: zhēnshí háishì shànliáng?",
      "Ài gèng xiàng yì zhǒng gǎnjué háishì yì zhǒng xuǎnzé?",
      "Méiyǒu tārén, nǐ néng zhēnzhèng liǎojiě zìjǐ ma?",
      "Rúguǒ nǐ bìxū yǒngyuǎn huó zài tóng yītiān, nà huì shì nǎ yītiān?",
      "Rúguǒ nǐ zhīdào zìjǐ bù huì shībài, nǐ huì zuò shénme?",
      "Nǐ xīwàng rénmen jì zhù nǐ de yī jiàn shì shì shénme?",
      "Nǐ gèng xiǎng bèi zūnzhòng háishì bèi xǐhuān?",
      "Rúguǒ nǐ néng chóngxīn kāishǐ rénshēng, nǐ huì gǎibiàn shénme?",
      "Yǒu shé me shì nǐ yǒngyuǎn wúfǎ lǐjiě de?",
      "Rúguǒ nǐ kěyǐ jiějué shìjiè shàng de yí gè wèntí, huì shì shénme?",
      "Tòngkǔ zài nǐ de rénshēng zhōng bànyǎn zhe zěnyàng de juésè?",
      "Nǐ juéde rén zhēnde kěyǐ gǎibiàn ma?",
      "Nǐ rènwéi zhìhuì de dìngyì shì shénme?",
      "Rénmen shēnghuó zhōng zuìdà de cuòjué shì shénme?",
      "Shíjiān hé jīnqián nǎgè gèng yǒu jiàzhí?",
      "Rúguǒ nǐ néng duì xiǎoshíhòu de zìjǐ shuō yī jù huà, huì shuō shénme?",
      "Nǐ juéde wǒmen shēnghuó zài xūnǐ shìjiè zhōng ma?",
      "Shì duì huánzhòng, háishì lǐjiě gèng zhòngyào?",
      "Nǐ xiāngxìn dàn dàduōshù rén bù xiāngxìn de yī jiàn shì shì shénme?",
      "Rúguǒ jīntiān shì nǐ shēngmìng de zuìhòu yītiān, nǐ huì zuò shénme?"
    ]
  },
  "Technology": {
    en: [
      "What’s a gadget you can’t live without?",
      "What’s your favorite app right now?",
      "Are you a Mac or PC person?",
      "If you could invent an app, what would it do?",
      "What's your opinion on AI taking over?",
      "Do you sleep next to your phone?",
      "What’s the oldest piece of tech you still use?",
      "Have you ever tried VR? What did you think?",
      "What's your screen time like?",
      "What’s a tech trend you find overrated?",
      "Do you prefer texting or voice messages?",
      "What was your first ever mobile phone?",
      "Would you try a smart home or do you prefer analog life?",
      "How often do you upgrade your phone?",
      "Have you ever fixed a gadget yourself?",
      "What’s the coolest tech gift you’ve ever received?",
      "Do you use any wearable tech?",
      "Would you try a robot assistant?",
      "Do you ever disconnect on purpose?",
      "What app do you open first in the morning?",
      "Have you tried any AI tools for fun?",
      "If you could automate one daily task, what would it be?",
      "Are you the tech support person for your family?",
      "Have you ever built your own PC or tech setup?",
      "If your phone could talk, what would it say about you?"
    ],
    zh: [
      "你最离不开的科技产品是什么？",
      "你现在最喜欢的应用程序是什么？",
      "你更喜欢用Mac还是PC？",
      "如果你能发明一个应用，它会做什么？",
      "你如何看待人工智能的普及？",
      "你睡觉时手机放在旁边吗？",
      "你还在用的最老的科技产品是什么？",
      "你用过虚拟现实（VR）吗？感觉怎么样？",
      "你每天的屏幕时间大概是多少？",
      "你觉得哪个科技潮流被高估了？",
      "你喜欢发短信还是语音信息？",
      "你人生中的第一部手机是什么？",
      "你想住智能家居还是喜欢传统生活？",
      "你多久换一次手机？",
      "你修过自己的电子产品吗？",
      "你收到过最酷的科技礼物是什么？",
      "你有没有用过智能穿戴设备？",
      "你愿意用机器人助手吗？",
      "你会故意“断网”吗？",
      "你早上第一打开的应用是什么？",
      "你有没有试过有趣的AI工具？",
      "如果能自动完成一件日常小事，你希望是什么？",
      "你是家里的“技术支持”吗？",
      "你有自己组装过电脑或设备吗？",
      "如果你的手机能说话，它会说你什么？"
    ],
    zh_roman: [
      "Nǐ zuì lí bù kāi de kējì chǎnpǐn shì shénme?",
      "Nǐ xiànzài zuì xǐhuān de yìngyòng chéngxù shì shénme?",
      "Nǐ gèng xǐhuān yòng Mac háishì PC?",
      "Rúguǒ nǐ néng fāmíng yīgè yìngyòng, tā huì zuò shénme?",
      "Nǐ rúhé kàndài réngōng zhìnéng de pǔjí?",
      "Nǐ shuìjiào shí shǒujī fàng zài pángbiān ma?",
      "Nǐ hái zài yòng de zuì lǎo de kējì chǎnpǐn shì shénme?",
      "Nǐ yòngguò xūnǐ xiànshí (VR) ma? Gǎnjué zěnmeyàng?",
      "Nǐ měitiān de píngmù shíjiān dàgài shì duōshǎo?",
      "Nǐ juéde nǎge kējì cháoliú bèi gāogū le?",
      "Nǐ xǐhuān fā duǎnxìn háishì yǔyīn xìnxī?",
      "Nǐ rénshēng zhōng de dì yī bù shǒujī shì shénme?",
      "Nǐ xiǎng zhù zài zhìnéng jiājū háishì xǐhuān chuántǒng shēnghuó?",
      "Nǐ duōjiǔ huàn yīcì shǒujī?",
      "Nǐ xiūguò zìjǐ de diànzǐ chǎnpǐn ma?",
      "Nǐ shōudào guò zuì kù de kējì lǐwù shì shénme?",
      "Nǐ yǒu méiyǒu yòngguò zhìnéng chuāndài shèbèi?",
      "Nǐ yuànyì yòng jīqìrén zhùshǒu ma?",
      "Nǐ huì gùyì 'duànwǎng' ma?",
      "Nǐ zǎoshang dì yī dǎkāi de yìngyòng shì shénme?",
      "Nǐ yǒu méiyǒu shìguò yǒuqù de AI gōngjù?",
      "Rúguǒ néng zìdòng wánchéng yī jiàn rìcháng xiǎoshì, nǐ xīwàng shì shénme?",
      "Nǐ shì jiālǐ de 'jìshù zhīchí' ma?",
      "Nǐ yǒu zìjǐ zǔzhuāng guò diànnǎo huò shèbèi ma?",
      "Rúguǒ nǐ de shǒujī néng shuōhuà, tā huì shuō nǐ shénme?"
    ]
  },
  "What If": {
    "en": [
      "What if you could time travel for one day — where and when would you go?",
      "What if you could have dinner with any historical figure — who would it be and why?",
      "What if money wasn’t an issue — what would you be doing right now?",
      "What if you woke up with a superpower — what would it be and how would you use it?",
      "What if you could live in any fictional universe — which one would you choose?",
      "What if you had to eat only one meal for the rest of your life — what would it be?",
      "What if you could switch lives with someone for a week — who would it be?",
      "What if you found a suitcase with a million dollars — what would you do?",
      "What if you could instantly learn any language — which would you pick and why?",
      "What if you could talk to animals — what’s the first thing you’d ask?",
      "What if you had 24 hours of complete freedom to do anything — what would you do?",
      "What if you had to start over in a new country — where would you go?",
      "What if you never had to sleep again — how would you spend that extra time?",
      "What if you could relive one day in your life — which would it be and why?",
      "What if your life was turned into a movie — what genre would it be?",
      "What if you could only keep one memory — what would it be?",
      "What if you could swap one of your skills for a new one — what would you trade?",
      "What if you had the chance to meet your future self — what would you ask?",
      "What if you could undo one decision — what would it be?",
      "What if you were invisible for a day — what would you do?"
    ],
    "zh": [
      "如果你能穿越一天，你会去哪里，什么时候？",
      "如果你能和一位历史人物共进晚餐，会是谁？为什么？",
      "如果钱不是问题，你现在会在做什么？",
      "如果你醒来拥有一种超能力，你希望是什么？你会怎么用它？",
      "如果你可以住在任何一个虚构的世界里，你会选哪个？",
      "如果你这辈子只能吃一种食物，那会是什么？",
      "如果你可以和一个人交换一周的人生，你会选谁？",
      "如果你捡到一个装有一百万美元的箱子，你会怎么做？",
      "如果你可以立刻学会一种语言，你会选哪种？为什么？",
      "如果你能和动物说话，你第一个想问它什么？",
      "如果你有24小时可以为所欲为，你会做什么？",
      "如果你必须去另一个国家重新开始，你会选哪里？",
      "如果你再也不用睡觉了，你会怎么利用这些额外的时间？",
      "如果你可以重温你生命中的一天，会是哪一天？为什么？",
      "如果你的人生被拍成电影，会是什么类型？",
      "如果你只能保留一个记忆，那会是什么？",
      "如果你可以用一个技能换一个新技能，你会换什么？",
      "如果你可以见到未来的自己，你会问什么？",
      "如果你能撤销一个决定，那会是什么？",
      "如果你可以隐身一天，你会做什么？"
    ],
    "zh_roman": [
      "Rúguǒ nǐ néng chuānyuè yītiān, nǐ huì qù nǎlǐ, shénme shíhòu?",
      "Rúguǒ nǐ néng hé yī wèi lìshǐ rénwù gòng jìn wǎncān, huì shì shéi? Wèishéme?",
      "Rúguǒ qián bù shì wèntí, nǐ xiànzài huì zài zuò shénme?",
      "Rúguǒ nǐ xǐng lái yǒngyǒu yī zhǒng chāonénglì, nǐ xīwàng shì shénme? Nǐ huì zěnme yòng tā?",
      "Rúguǒ nǐ kěyǐ zhù zài rènhé yīgè xūgòu de shìjiè lǐ, nǐ huì xuǎn nǎgè?",
      "Rúguǒ nǐ zhè bèizi zhǐ néng chī yī zhǒng shíwù, nà huì shì shénme?",
      "Rúguǒ nǐ kěyǐ hé yīgè rén jiāohuàn yī zhōu de rénshēng, nǐ huì xuǎn shéi?",
      "Rúguǒ nǐ jiǎndào yīgè zhuāng yǒu yībǎi wàn měiyuán de xiāngzi, nǐ huì zěnme zuò?",
      "Rúguǒ nǐ kěyǐ lìkè xuéhuì yī zhǒng yǔyán, nǐ huì xuǎn nǎ zhǒng? Wèishéme?",
      "Rúguǒ nǐ néng hé dòngwù shuōhuà, nǐ dì yī gè xiǎng wèn tā shénme?",
      "Rúguǒ nǐ yǒu 24 xiǎoshí kěyǐ wéi suǒ yù wéi, nǐ huì zuò shénme?",
      "Rúguǒ nǐ bìxū qù lìng yīgè guójiā chóngxīn kāishǐ, nǐ huì xuǎn nǎlǐ?",
      "Rúguǒ nǐ zàiyě bùyòng shuìjiào le, nǐ huì zěnme lìyòng zhèxiē èrzhì de shíjiān?",
      "Rúguǒ nǐ kěyǐ chóng wēn nǐ shēngmìng zhōng de yītiān, huì shì nǎ yītiān? Wèishéme?",
      "Rúguǒ nǐ de rénshēng bèi pāi chéng diànyǐng, huì shì shénme lèixíng?",
      "Rúguǒ nǐ zhǐ néng bǎoliú yīgè jìyì, nà huì shì shénme?",
      "Rúguǒ nǐ kěyǐ yòng yīgè jìnéng huàn yīgè xīn jìnéng, nǐ huì huàn shénme?",
      "Rúguǒ nǐ kěyǐ jiàn dào wèilái de zìjǐ, nǐ huì wèn shénme?",
      "Rúguǒ nǐ néng chèxiāo yīgè juédìng, nà huì shì shénme?",
      "Rúguǒ nǐ kěyǐ yǐnshēn yītiān, nǐ huì zuò shénme?"
    ]
  },
  "Dating History": {
    "en": [
      "How many serious relationships have you had?",
      "When was your last relationship?",
      "Have you ever been engaged or married?",
      "Have you lived with a partner before? What was that like?",
      "Do you believe in taking a break during a relationship?",
      "What do you think about pre-marital sex?",
      "Have you ever gotten back with an ex?",
      "Do you usually stay friends with your exes?",
      "What’s something you learned from a past relationship?",
      "Have you ever ghosted or been ghosted?",
      "Would you date someone who’s never been in a relationship?",
      "How long does it usually take you to fall for someone?",
      "Do you believe love should feel easy or take work?",
      "How important is physical intimacy to you in a relationship?",
      "Would you move for love?"
    ],
    "zh": [
      "你有过几段认真的恋爱？",
      "你上一次恋爱是什么时候？",
      "你曾经订婚或结过婚吗？",
      "你和伴侣同居过吗？感觉如何？",
      "你相信感情中需要“暂时分开”吗？",
      "你怎么看婚前性行为？",
      "你有没有和前任复合过？",
      "你通常会和前任做朋友吗？",
      "你从过去的恋情中学到什么？",
      "你有没有被“消失式分手”或这样对别人？",
      "你会和从没谈过恋爱的人约会吗？",
      "你通常多久会对一个人动心？",
      "你觉得爱情应该是轻松的，还是需要努力的？",
      "身体亲密对你来说在恋爱中有多重要？",
      "你愿意为爱搬家吗？"
    ],
    "zh_roman": [
      "Nǐ yǒuguò jǐ duàn rènzhēn de liàn'ài?",
      "Nǐ shàng yī cì liàn'ài shì shénme shíhòu?",
      "Nǐ céngjīng dìnghūn huò jiéguò hūn ma?",
      "Nǐ hé bànlǚ tóngjū guò ma? Gǎnjué rúhé?",
      "Nǐ xiāngxìn gǎnqíng zhōng xūyào 'zànshí fēnkāi' ma?",
      "Nǐ zěnme kàn hūnqián xìng xíngwéi?",
      "Nǐ yǒu méiyǒu hé qiánrèn fùhé guò?",
      "Nǐ tōngcháng huì hé qiánrèn zuò péngyǒu ma?",
      "Nǐ cóng guòqù de liànqíng zhōng xué dào shénme?",
      "Nǐ yǒu méiyǒu bèi 'xiāoshīshì fēnshǒu' huò zhèyàng duìguò biérén?",
      "Nǐ huì hé cóng méi tán guò liàn'ài de rén yuēhuì ma?",
      "Nǐ tōngcháng duōjiǔ huì duì yīgè rén dòngxīn?",
      "Nǐ juéde àiqíng yīnggāi shì qīngsōng de háishì xūyào nǔlì de?",
      "Shēntǐ qīnmì duì nǐ lái shuō zài liàn'ài zhōng yǒu duō zhòngyào?",
      "Nǐ yuànyì wèi ài bānjiā ma?"
    ]
  },
  "Dating": {
    "en": [
      "What do you look for in a partner?",
      "What’s your idea of a perfect date?",
      "Would you rather stay in or go out on a date?",
      "Have you ever had a crush on someone unexpected?",
      "What’s your love language?",
      "Do you believe in love at first sight?",
      "What’s the most romantic thing someone has done for you?",
      "What’s a dating red flag for you?",
      "What’s your biggest turn-on or turn-off?",
      "What do you think makes a relationship last?",
      "What kind of dates do you enjoy the most?",
      "Have you ever made the first move?",
      "What’s something you wish people would stop doing on dates?",
      "Would you date someone who doesn’t share your interests?",
      "What’s your biggest dating green flag?",
      "Do you prefer texting or calling when getting to know someone?",
      "How long do you usually take before calling someone your partner?",
      "What’s your go-to date night outfit?",
      "How do you handle awkward silences on a date?",
      "Have you ever had a really bad date? What happened?",
      "How do you feel about dating apps?",
      "Do you like being surprised in relationships?",
      "What’s your opinion on public displays of affection?",
      "How would your best friend describe your dating style?",
      "Do you believe people can change for love?",
      "Would you rather date someone similar to you or someone very different?",
      "What’s your idea of a meaningful connection?",
      "How do you usually flirt?",
      "What’s the nicest compliment you've received from a date?",
      "How do you know when you're really into someone?",
      "What’s your ideal first message on a dating app?",
      "Have you ever ghosted or been ghosted?",
      "Do you like slow-burn or instant chemistry?",
      "How do you define emotional intimacy?",
      "What’s something you find super attractive (but others might not)?",
      "Would you go on a blind date?",
      "Do you enjoy planning dates or being surprised?",
      "Would you rather be single forever or settle for someone just okay?",
      "What’s one thing you wish people asked more on dates?",
      "What’s something romantic you’ve always wanted to do?"
    ],
    "zh": [
      "你在伴侣身上最看重什么？",
      "你心目中完美的约会是怎样的？",
      "你更喜欢在家约会还是外出约会？",
      "你有没有暗恋过一个很意外的人？",
      "你的爱情语言是什么？",
      "你相信一见钟情吗？",
      "别人为你做过最浪漫的事是什么？",
      "你眼中的约会红旗是什么？",
      "什么行为最吸引你或让你立刻冷掉？",
      "你认为一段感情要如何才能长久？",
      "你最喜欢哪种类型的约会？",
      "你有没有主动追求过别人？",
      "你希望别人在约会中别再做什么事？",
      "你会和一个兴趣完全不同的人约会吗？",
      "你觉得约会中最明显的好信号是什么？",
      "你在了解一个人时更喜欢发信息还是打电话？",
      "你通常多久后会把对方称为另一半？",
      "你约会时最常穿什么衣服？",
      "当约会时遇到冷场你会怎么做？",
      "你有没有经历过很糟糕的约会？发生了什么？",
      "你怎么看待交友软件？",
      "你喜欢在感情中被惊喜吗？",
      "你怎么看待公共场合的亲昵举动？",
      "你最好的朋友会怎么形容你的约会风格？",
      "你相信人会为爱改变吗？",
      "你更愿意和跟你相似还是完全不同的人约会？",
      "你认为什么样的关系才算有意义的连接？",
      "你通常怎么调情？",
      "你从约会对象那里收到过最赞的夸奖是什么？",
      "你怎么判断自己是真的喜欢一个人？",
      "你觉得在交友软件上第一条消息应该说什么？",
      "你有没有被人突然断联或自己断联过别人？",
      "你喜欢慢慢来还是一见如故的感觉？",
      "你怎么定义情感亲密？",
      "有没有别人不太在意但你觉得超级吸引的点？",
      "你愿意参加相亲吗？",
      "你喜欢自己策划约会还是被惊喜安排？",
      "你愿意一直单身还是和一个普通的人将就？",
      "你希望别人约会时多问你什么问题？",
      "你一直想尝试但还没做过的浪漫事是什么？"
    ],
    "zh_roman": [
      "Nǐ zài bànlǚ shēnshang zuì kànzhòng shénme?",
      "Nǐ xīnmù zhōng wánměi de yuēhuì shì zěnyàng de?",
      "Nǐ gèng xǐhuān zài jiā yuēhuì háishì wàichū yuēhuì?",
      "Nǐ yǒu méiyǒu ànliàn guò yīgè hěn yìwài de rén?",
      "Nǐ de àiqíng yǔyán shì shénme?",
      "Nǐ xiāngxìn yījiànzhōngqíng ma?",
      "Biérén wèi nǐ zuò guò zuì làngmàn de shì shì shénme?",
      "Nǐ yǎnzhōng de yuēhuì hóngqí shì shénme?",
      "Shénme xíngwéi zuì xīyǐn nǐ huò ràng nǐ lìkè lěngdiào?",
      "Nǐ rènwéi yīduàn gǎnqíng yào rúhé cáinéng chángjiǔ?",
      "Nǐ zuì xǐhuān nǎ zhǒng lèixíng de yuēhuì?",
      "Nǐ yǒu méiyǒu zhǔdòng zhuīqiú guò biérén?",
      "Nǐ xīwàng biérén zài yuēhuì zhōng bié zài zuò shénme shì?",
      "Nǐ huì hé yīgè xìngqù wánquán bù tóng de rén yuēhuì ma?",
      "Nǐ juédé yuēhuì zhōng zuì míngxiǎn de hǎo xìnhào shì shénme?",
      "Nǐ zài liǎojiě yīgè rén shí gèng xǐhuān fā xìnxī háishì dǎ diànhuà?",
      "Nǐ tōngcháng duōjiǔ hòu huì bǎ duìfāng chēng wèi lìng yībàn?",
      "Nǐ yuēhuì shí zuì cháng chuān shénme yīfú?",
      "Dāng yuēhuì shí yù dào lěngchǎng nǐ huì zěnme zuò?",
      "Nǐ yǒu méiyǒu jīnglì guò hěn zāogāo de yuēhuì? Fāshēng le shénme?",
      "Nǐ zěnme kàndài jiāoyǒu ruǎnjiàn?",
      "Nǐ xǐhuān zài gǎnqíng zhōng bèi jīngxǐ ma?",
      "Nǐ zěnme kàndài gōnggòng chǎnghé de qīnnì jǔdòng?",
      "Nǐ zuì hǎo de péngyǒu huì zěnme xíngróng nǐ de yuēhuì fēnggé?",
      "Nǐ xiāngxìn rén huì wèi ài gǎibiàn ma?",
      "Nǐ gèng yuànyì hé gēn nǐ xiāngsì háishì wánquán bùtóng de rén yuēhuì?",
      "Nǐ rènwéi shénme yàng de guānxì cái suàn yǒuyìyì de liánjié?",
      "Nǐ tōngcháng zěnme tiáoqíng?",
      "Nǐ cóng yuēhuì duìxiàng nàlǐ shōudào guò zuì zàn de kuājiǎng shì shénme?",
      "Nǐ zěnme pànduàn zìjǐ shì zhēn de xǐhuān yīgè rén?",
      "Nǐ juédé zài jiāoyǒu ruǎnjiàn shàng dì yītiáo xiāoxī yīnggāi shuō shénme?",
      "Nǐ yǒu méiyǒu bèi rén tūrán duànlián huò zìjǐ duànlián guò biérén?",
      "Nǐ xǐhuān mànmàn lái háishì yījiàn rúgù de gǎnjué?",
      "Nǐ zěnme dìngyì qínggǎn qīnmì?",
      "Yǒu méiyǒu biérén bù tài zàiyì dàn nǐ juédé chāojí xīyǐn de diǎn?",
      "Nǐ yuànyì cānjiā xiāngqīn ma?",
      "Nǐ xǐhuān zìjǐ cèhuà yuēhuì háishì bèi jīngxǐ ānpái?",
      "Nǐ yuànyì yīzhí dānshēn háishì hé yīgè pǔtōng de rén jiāngjiù?",
      "Nǐ xīwàng biérén yuēhuì shí duō wèn nǐ shénme wèntí?",
      "Nǐ yīzhí xiǎng chángshì dàn hái méi zuòguò de làngmàn shì shì shénme?"
    ]
  },
  "First Time": {
    "en": [
      "What was your first job, and how did you get it?",
      "Do you remember your first crush?",
      "When was your first kiss, and what was it like?",
      "What was the first concert you ever attended?",
      "What was your first time traveling alone like?",
      "What was the first big decision you ever made on your own?",
      "What’s the first movie you remember watching in a cinema?",
      "What was the first dish you ever cooked by yourself?",
      "Do you remember your first day at school? How did it go?",
      "When was the first time you felt truly independent?",
      "Who was your first best friend, and how did you meet?",
      "What was your first phone, and what did you use it for the most?",
      "What’s the first book you remember loving?",
      "What was your first heartbreak?",
      "Do you remember your first trip on a plane?",
      "What’s the first time you stayed up all night, and why?",
      "What was your first big purchase with your own money?",
      "What was the first pet you ever had?",
      "What’s the first compliment you remember receiving?",
      "What was your first social media account?"
    ],
    "zh": [
      "你的第一份工作是什么？你是怎么得到的？",
      "你还记得你第一次暗恋的人吗？",
      "你第一次接吻是什么时候？感觉如何？",
      "你第一次去的演唱会是什么？",
      "你第一次一个人旅行是怎样的经历？",
      "你第一次独立做出的重大决定是什么？",
      "你第一次在电影院看电影是看什么？",
      "你第一次自己做的一道菜是什么？",
      "你还记得你第一天上学的情景吗？",
      "你第一次真正感到独立是什么时候？",
      "你第一个最好的朋友是谁？你们是怎么认识的？",
      "你第一部手机是什么？你最常用它来做什么？",
      "你最早喜欢的一本书是什么？",
      "你第一次心碎是什么时候？",
      "你还记得你第一次坐飞机吗？",
      "你第一次熬夜通宵是什么时候？为什么？",
      "你第一次用自己的钱买的大件物品是什么？",
      "你养的第一个宠物是什么？",
      "你记得收到的第一句赞美吗？",
      "你用的第一个社交媒体账号是什么？"
    ],
    "zh_roman": [
      "Nǐ de dì yī fèn gōngzuò shì shénme? Nǐ shì zěnme dédào de?",
      "Nǐ hái jìdé nǐ dì yī cì ànliàn de rén ma?",
      "Nǐ dì yī cì jiēwěn shì shénme shíhòu? Gǎnjué rúhé?",
      "Nǐ dì yī cì qù de yǎnchànghuì shì shénme?",
      "Nǐ dì yī cì yīgè rén lǚxíng shì zěnyàng de jīnglì?",
      "Nǐ dì yī cì dúlì zuòchū de zhòngdà juédìng shì shénme?",
      "Nǐ dì yī cì zài diànyǐngyuàn kàn diànyǐng shì kàn shénme?",
      "Nǐ dì yī cì zìjǐ zuò de yī dào cài shì shénme?",
      "Nǐ hái jìdé nǐ dì yī tiān shàngxué de qíngjǐng ma?",
      "Nǐ dì yī cì zhēnzhèng gǎndào dúlì shì shénme shíhòu?",
      "Nǐ dì yī gè zuì hǎo de péngyǒu shì shéi? Nǐmen shì zěnme rènshí de?",
      "Nǐ dì yī bù shǒujī shì shénme? Nǐ zuì cháng yòng tā lái zuò shénme?",
      "Nǐ zuì zǎo xǐhuān de yī běn shū shì shénme?",
      "Nǐ dì yī cì xīn suì shì shénme shíhòu?",
      "Nǐ hái jìdé nǐ dì yī cì zuò fēijī ma?",
      "Nǐ dì yī cì áoyè tōngxiāo shì shénme shíhòu? Wèishéme?",
      "Nǐ dì yī cì yòng zìjǐ de qián mǎi de dàjiàn wùpǐn shì shénme?",
      "Nǐ yǎng de dì yī gè chǒngwù shì shénme?",
      "Nǐ jìdé shōudào de dì yī jù zànměi ma?",
      "Nǐ yòng de dì yī gè shèjiāo méitǐ zhànghào shì shénme?"
    ]
  }
  // ,
  // "Random": {}
};

const romanization = {
  "Get To Know You": "Rèn shí nǐ", // 认识你
  "Hobbies": "Ài hào",
  "Fun Facts": "Qù shì",
  "Career": "Zhí yè",
  "Travel": "Lǚ xíng",
  "Reflection": "Sīkǎo rénshēng", //思考人生
  "Technology": "Kē jì",
  "Dating History": "Qínggǎn lìchéng", // 情感历程
  "Dating": "yuē huì", //约会,
  "What If": "Jiǎ rú", //假如
  "First Time": "Dì yī cì " // 第一次
  // "Adult": "Chéng rèn",
  // "Attraction": "Xī yǐn",
  // "Intimacy": "Qīn mì"
};
